base/urls.py
from django.urls import path
from base.views import home_page

app_name = 'base'

urlpatterns = [
    path('', home_page, name='home_page'),
]

contact/urls.py
from django.urls import path

from contact import views


app_name = 'contact'

urlpatterns = [
    path("", views.contact, name="contact"),
]

nirmaldeep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('services/', include('services.urls', namespace='services')),
    path('contact/', include('contact.urls', namespace='contact')),
]

handler404 = 'base.views.handler404'
handler500 = 'base.views.handler500'

services/urls.py
from django.urls import path

from services import views


app_name = 'services'

urlpatterns = [
    path("", views.services_list, name="services_list"),
    path("<int:id>/", views.services_detail, name="services_detail"),

]

base/models.py
from django.db import models

# Create your models here.

class EnglishQuoteManager(models.Manager):
    def get_queryset(self):
        return super(EnglishQuoteManager, self).get_queryset()\
            .filter(language="english")

class NepaliQuoteManager(models.Manager):
    def get_queryset(self):
        return super(NepaliQuoteManager, self).get_queryset()\
            .filter(language="nepali")

class Quote(models.Model):
    LANGUAGE = (
        ("english", "English"),
        ("nepali", "Nepali")
    )

    quote = models.TextField(max_length=1500)
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    language = models.CharField(choices=LANGUAGE, default="english", max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()
    english_quotes = EnglishQuoteManager()
    nepali_quotes = NepaliQuoteManager()
    class Meta:
        ordering=("-created",)
    
    def __str__(self):
        return f"Quote by {self.name}"

contact/models.py
from django.db import models

# Create your models here.

class ContactedBy(models.Model):
    CONTACT_MODE_CHOICES = (
        ('telegram', 'Telegram'),
        ('facebook_messenger', 'Facebook Messenger'),
        ('whatsapp', 'Whatsapp'),
        ('viber', 'Viber'),
        ('gmail', 'Gmail'),
        ('phone', 'Phone Number')
    )

    full_name = models.CharField(max_length=50)
    contact_mode = models.CharField(max_length=50, choices=CONTACT_MODE_CHOICES, default='whatsapp')
    contact_info = models.CharField(max_length=250)
    message = models.TextField(max_length=1000)
    message_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)
    
    def __str__(self):
        return f"{self.full_name} -> {self.contact_mode} -> {self.contact_info}"

services/models.py
from django.db import models

# Create your models here.

class ServiceCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Services(models.Model):
    name = models.CharField(max_length=250)
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE, related_name="services")
    description = models.TextField(max_length=5000, blank=True)
    picture_url = models.URLField(max_length=500, blank=True)
    youtube_video_url = models.URLField(max_length=500, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', 'category',)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms

from contact.models import ContactedBy

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactedBy
        fields = ('full_name', 'contact_mode', 'contact_info', 'message')
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'input is-medium', 'placeholder': 'Full Name'}),
            'contact_info': forms.TextInput(attrs={'class': 'input is-medium', 'placeholder': 'Contact Info'}),
            'message': forms.Textarea(attrs={'class': 'textarea has-fixed-size is-medium', 'placeholder': 'Type your message here...'}),
        }

base/views.py
from django.shortcuts import render
from django.template import RequestContext

# Create your views here.

def home_page(request):
    return render(request, "base/index.html")


def handler404(request, *args, **argv):
    response = render(request, 'base/404.html')
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render(request, 'base/500.html')
    response.status_code = 500
    return response

contact/views.py
from django.shortcuts import render

from contact.forms import ContactForm
from contact.models import ContactedBy


# Create your views here.

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = ContactedBy()
            contact.full_name = form.cleaned_data['full_name']
            contact.contact_mode = form.cleaned_data['contact_mode']
            contact.contact_info = form.cleaned_data['contact_info']
            contact.message = form.cleaned_data['message']
            contact.save()
            return render(request, 'contact/thanks.html', {'active': 'contact'})
    else:
        form = ContactForm()
    return render(request, 'contact/contact.html', {'form': form, 'active': 'contact'})

services/views.py
from django.shortcuts import render, get_object_or_404

from services.models import ServiceCategory, Services

# Create your views here.


def services_list(request):
    categories = ServiceCategory.objects.all()
    if categories:
        services = {category: Services.objects.filter(category=category)  for category in categories}
    else:
        services = {}
    
    return render(
        request,
        template_name="services/list.html",
        context={
            "services": services,
            "active": "services",
        }
    )


def services_detail(request, id):
    service = get_object_or_404(klass=Services, pk=id)
    return render(
        request,
        template_name="services/detail.html",
        context={
            "service": service,
            "active": "services",
        }
    )

base/templates/base/base.html
{% load static %}
{% load django_simple_bulma %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Nirmal Deep Reiki | {% if title %} | {{ title }} {% endif %} </title>

  <!--Custom Font Import-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">

  <!-- Fontawesome Embed -->
  <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
  
  <!--Custom CSS-->
  <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}" />

  <!-- Bulma CSS -->
  {% bulma %}
  
  {% block extraheadelements %}{% endblock extraheadelements %}
</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
          <a href="{% url 'base:home_page' %}" class="navbar-item">
              <img src="{% static 'base/img/logo.png' %}"  width="" height="" alt="Nirmal Deep">
          </a>
          
          <div role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </div>
      </div>      
      
      <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
          <!-- navbar items -->
        </div>
      
        <div class="navbar-end is-size-4">
          <a href="" class="navbar-item">
            Details
          </a>
          <a href="{% url 'contact:contact' %}" class="navbar-item {% if active == 'contact' %} is-active {% endif %}">
            Contact
          </a>
          <a href="{% url 'services:services_list' %}" class="navbar-item {% if active == 'services' %} is-active {% endif %}">
            Services
          </a>
          <a href="" class="navbar-item">
            Members
          </a>
          <a href="" class="navbar-item">
            Events
          </a>
          <a href="" class="navbar-item">
            Notices
          </a>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock content %}

    {# Footer #}

    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
          <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
          is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
        </p>
      </div>
    </footer>
</body>

<script type="text/javascript" src="{% static 'base/js/base.js'%}"></script>

{% block postbodyelements %}
{% endblock postbodyelements %}

</html>

base/templates/base/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
{% endblock content %}

contact/templates/contact/contact.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <section class="hero is-fullheight">
		<div class="hero-body">
			<div class="container has-text-centered">
				<div class="columns is-8 is-variable ">
					<div class="column is-one-thirds has-text-left">
						<h1 class="is-size-1">Contact Us</h1>
                        <hr/>
						<p class="is-size-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla eligendi soluta
							voluptate facere molestiae consequatur.</p>
						<div class="social-media">
							<a href="https://facebook.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-facebook fa-xl"></i></a>
							<a href="https://instagram.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-instagram fa-xl"></i></a>
							<a href="https://youtube.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-youtube fa-xl"></i></a>
                            <a href="https://facebook.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-facebook-messenger fa-xl"></i></a>
							<a href="https://instagram.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-viber fa-xl"></i></a>
							<a href="https://youtube.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-whatsapp fa-xl"></i></a>
                            <a href="https://facebook.com" target="_blank" class="button is-light is-medium"><i class="fa-brands fa-telegram fa-xl"></i></a>
						</div>
					</div>
					<div class="column is-two-third has-text-left">
                        <form method="POST">
                            <div class="field">
                                <label for="id_full_name" class="label is-medium">Full name:</label>
                                <div class="control">
                                    {{ form.full_name }}
                                </div>
                            </div>

                            <div class="field">
                                <label for="id_contact_info" class="label is-medium">Contact Information</label>
                                <div class="field is-grouped is-grouped-multiline is-horizontal">
                                    <div class="control">
                                        <span class="select is-medium">
                                            {{form.contact_mode}}
                                        </span>
                                    </div>
                                    <div class="control is-expanded">
                                        {{ form.contact_info }}
                                    </div>
                                </div>
                                <p class="help has-text-black">Please select appropriate contact mode and provide the correct contact information.</p>
                            </div>

                            <div class="field">
                                <label for="id_message" class="label is-medium">Message</label>
                                <div class="control">
                                    {{ form.message }}
                                </div>
                            </div>
                            {% csrf_token %}
                            <div class="control">
                                        <button type="submit" class="button is-link is-fullwidth has-text-weight-medium is-medium">Send Message</button>
                            </div>
                        </form>

					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

contact/templates/contact/thanks.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <h1 class="is-size-1"> Contact Us </h1>
    <hr>

    <p class="is-size-4"> Thank you for your message! We will get back to you as soon as possible. </p>
{% endblock content %}

services/templates/services/detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="section">
        <h1 class="is-size-1">{{service.name}}</h1>
        <hr>

        <div class="columns">
            <div class="column is-one-quarter"></div>
            <div class="column">
                <img src="{{ service.picture_url }}" alt="{{ service.name }}">
            </div>
            <div class="column is-one-quarter"></div>
        </div>

        <p class="is-size-4">
            {{ service.description}}
        </p>
   </div>

{% endblock content %}

services/templates/services/list.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="section">
        {% for category, service_list in services.items %}
            <h1 class="is-size-1">{{category}}</h1>
            <hr>

            <div class="columns">
                {% for service in service_list %}
                    <div class="column">
                        <div class="card">
                            <div class="card-image">
                              <figure class="image is-3by2">
                                <img src="{{ service.picture_url }}" alt="{{ service.name }}" width="480" height="200">
                              </figure>
                            </div>
                            <div class="card-content has-text-black">
                                <p class="title is-4">{{ service.name }}</p>
                                  <div class="content">
                                    {{ service.description|truncatechars:200 }}
                                  </div>
                                <br>
                                <a class="button is-primary" href="{% url 'services:services_detail' service.id %}">Learn more</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    {% endfor %}
    </div>

{% endblock content %}